index:
    path: /
    controller: App\Controller\IndexController::index
# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_lucky_numbers:
    path: /lucky/number/{max}
    controller: App\Controller\LuckyController::numbers
